spring:
    application:
        name: api-gateway
    cloud:
        gateway:
            routes:
                - id: CONTENT-MS
                  uri: lb://CONTENT-MS
                  predicates:
                      - Path=/api/content/**



server:
    port: 8080